#!/bin/bash

todate=$2
path=$1

files=(/home/$USER/$path/*)
nooffiles=${#files[@]}
dates=()

for (( i=0; i<nooffiles; i++ )); do
  
	dates[i]=$(date -r ${files[i]} +"%Y%m%d");  

	if [[ ${dates[i]} -gt $todate ]];
	  then 
	    echo "${files[i]} ---- ${dates[i]}";

	fi

done
