#!/bin/bash

echo 'Date format: YYYYmmDD' 
todate=$(date -d 20160602 +"%Y%m%d") 
echo 'Given date: ' $todate
echo ''

files=(*)
nooffiles=${#files[@]}
dates=()

i=0
option=0
while [[ $option!=1 && $option!=2 ]]
do
  echo '';
  echo "Select what you want to search: <1> Greater <2> Less";
  echo "'Ctrl + C' to exit"
  read option;


  if [ $option -eq 1 ]
    then
      for (( i=0; i<nooffiles; i++ )); do
  
        dates[i]=$(date -r ${files[i]} +"%Y%m%d");  
        

        if [[ ${dates[i]} -gt $todate ]];
          then 
            echo '';
            echo ${files[i]} 'last modified date is greater than the given date: ' ${dates[i]};
            echo '';

          else
            echo '';
            echo ${files[i]} 'last modified date is not greater than the given date: ' ${dates[i]};
            echo '';
        fi

      done
  fi


  if [ $option -eq 2 ]
    then
      for (( i=0; i<nooffiles; i++ )); do
  
        dates[i]=$(date -r ${files[i]} +"%Y%m%d");  
        
        if [[ ${dates[i]} -lt $todate ]];
          then 
            echo '';
            echo ${files[i]} 'last modified date is less than the given date: ' ${dates[i]};
            echo '';

          else
            echo '';
            echo ${files[i]} 'last modified date is not less than the given date: ' ${dates[i]};
            echo '';
        fi

      done
  fi

done


