#!/bin/bash

files=(*)
dates=()

for (( i = 0; i<${#files[@]}; i++ ))
do
	dates[$i]=$(date -r ${files[i]} +"%Y%m%d");
	
done

# Sorting 
echo "The list of files sorted by last modified dates: "
for (( i = 0; i<${#files[@]} ; i++ ))
do

	for (( j = $i; j<${#files[@]}; j++ ))
	do
		if [[ ${dates[$i]} -gt ${dates[$j]} ]]; then
			t=${dates[$i]}
			dates[$i]=${dates[$j]}
			dates[$j]=$t

			t2=${files[$i]}
			files[$i]=${files[$j]}
			files[$j]=$t2
		fi

	done	

	echo ${files[$i]};
	# echo ${dates[$i]};
	
done | tee sort_modified_date_output.txt

