#!/bin/bash

files=(*)
dates=()

for (( i = 0; i<${#files[@]}; i++ ))
do
   dates[$i]=$(stat -c%s "${files[$i]}");
   
done

# Sorting of numbers
for (( i = 0; i<${#files[@]} ; i++ ))
do

   for (( j = $i; j<${#files[@]}; j++ ))
   do
      if [[ ${dates[$i]} -gt ${dates[$j]} ]]; then
         t=${dates[$i]}
         dates[$i]=${dates[$j]}
         dates[$j]=$t
      fi

   done  

   #echo ${files[$i]};
   echo ${dates[$i]};
   
done 

